export const employeeMockData = [
  {
    src: "/images/staff1.jpg",
    alt: "Фото Козловского Дмитрия Альбертовича",
    name: "Козловский Дмитрий Альбертович",
    job: "Директор",
    phone: "+375 (2340) 6-20-00",
    email: "d.kozlovskiy@stalgrit.by",
  },
  {
    src: "/images/staff2.jpg",
    alt: "Фото Сазонова Ивана Николаевича",
    name: "Сазонов Иван Николаевич",
    job: "Главный инженер",
    phone: "+375 (29) 623-32-30",
    email: "info@stalgrit.by",
  },
  {
    src: "/images/staff3.jpg",
    alt: "Фото Вашкова Ивана Адамовича",
    name: "Вашков Иван Адамович",
    job: "Заместитель директора по экономике",
    phone: "+375 (44) 777-7012",
    email: "i.vashkov@stalgrit.by",
  },
  {
    src: "/images/staff4.jpg",
    alt: "Фото Гришковой Натальи Валерьевны",
    name: "Гришкова Наталья Валерьевна",
    job: "Экономист по сбыту",
    phone: "+375 (29) 692-16-18",
    email: "vesstalgrit@mail.ru",
  },
  {
    src: "/images/staff5.jpg",
    alt: "Фото Коваленко Виктории Николаевны",
    name: "Коваленко Виктория Николаевна",
    job: "Главный бухгалтер",
    phone: "+375 (2340) 6-20-00",
    email: "v.kovalenko@stalgrit.by",
  },
  {
    src: "/images/staff6.jpg",
    alt: "Фото Савенок Натальи Алексеевны",
    name: "Савенок Наталья Алексеевна",
    job: "Инспектор по кадрам",
    phone: "+375 (2340) 6-20-00",
    email: "ipstal@mail.ru",
  },
]